# Generated by Django 5.2.3 on 2025-06-18 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatgroup_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='group_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_image0', to='chat.image'),
        ),
    ]
