# Generated by Django 5.2.3 on 2025-06-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatgroup_group_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('regular', 'regular'), ('admin', 'admin'), ('reader', 'reader')], default='regular', max_length=100),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
