# Generated by Django 5.2.3 on 2025-07-08 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_groupchat_sent_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member',
        ),
        migrations.AddField(
            model_name='member',
            name='member',
            field=models.ManyToManyField(related_name='joined_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
