# Generated by Django 5.2.3 on 2025-07-08 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_member_member_member_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_image', to='chat.image'),
        ),
    ]
