# Generated by Django 5.2.3 on 2025-07-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatgroup_uid_alter_groupchat_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
