# Generated by Django 5.2.3 on 2025-08-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='private', max_length=100),
        ),
    ]
