# Generated by Django 5.2.3 on 2025-08-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_chatgroup_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='image_message',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
