# Generated by Django 5.2.3 on 2025-08-24 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_groupchat_image_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='deleted_for',
            field=models.ManyToManyField(related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
