# Generated by Django 5.2.3 on 2025-08-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_groupchat_deleted_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchat',
            name='image_message',
        ),
        migrations.AddField(
            model_name='groupchat',
            name='file_message',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
