# Generated by Django 5.2.3 on 2025-08-27 07:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_groupchat_image_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('sender', 'group')},
        ),
    ]
