# Generated by Django 5.2.3 on 2025-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_joinrequest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='message_type',
            field=models.CharField(choices=[('text', 'text'), ('file', 'file'), ('form', 'form')], max_length=100),
        ),
    ]
