# Generated by Django 5.2.3 on 2025-06-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarifiedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('varified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cnfuser',
            options={'verbose_name': 'CNFUser'},
        ),
        migrations.RemoveField(
            model_name='cnfuser',
            name='otp',
        ),
    ]
