# Generated by Django 5.2.3 on 2025-06-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_varifiedemail_alter_cnfuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnfuser',
            name='varified',
        ),
    ]
