# Generated by Django 5.2.3 on 2025-06-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_cnfuser_varified'),
    ]

    operations = [
        migrations.AddField(
            model_name='varifiedemail',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
