# Generated by Django 5.2.3 on 2025-06-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_varifiedemail_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varifiedemail',
            name='otp',
        ),
    ]
