# Generated by Django 5.2.3 on 2025-06-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_varifiedemail_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VarifiedEmail',
            new_name='VerifiedEmail',
        ),
        migrations.RenameField(
            model_name='verifiedemail',
            old_name='varified',
            new_name='verified',
        ),
    ]
